### ISSUE TITLE
Fix get_random_rpc so that it will choose an RPC that won't fail to connect

### ISSUE THREAD

**Issue by dtdang** [ApeWorX/evmchains#13]
Update get_random_rpc so that it doesn't choose an rpc that requires a token that the user doesn't have causing an error like `ape.exceptions.ProviderError: No (supported) node found on 'https://sepolia.infura.io/[hidden]'.`

**Comment by mikeshultz** [comment]
Here's the offending line:

https://github.com/ApeWorX/evmchains/blob/79da8102cb207c784f3b347e8766bec77ee65924/evmchains/chains.py#L532

Agreed, this is a bug.  

Unfortunately, there's a few networks where the Infura node is one of 2 available public nodes.  We could have that function look for a matching env var during selection and return it if possible.  Or just filter them out from the list entirely.  I don't have strong feelings either way.  Thoughts?

**Comment by dtdang** [comment]
It's not just the infura rpc that shows this error. I've also noticed it when it is trying to connect with tenderly node as well 
["https://sepolia.gateway.tenderly.co",](https://github.com/ApeWorX/evmchains/blob/79da8102cb207c784f3b347e8766bec77ee65924/evmchains/chains.py#L533C17-L533C55)

Not sure if there are more rpcs that are affected by this currently.

**Comment by mikeshultz** [comment]
> It's not just the infura rpc that shows this error. I've also noticed it when it is trying to connect with tenderly node as well ["https://sepolia.gateway.tenderly.co",](https://github.com/ApeWorX/evmchains/blob/79da8102cb207c784f3b347e8766bec77ee65924/evmchains/chains.py#L533C17-L533C55)

The linked tenderly RPC doesn't have the same issue with the required keys.  If you can repro and confirm that error, can you post it?  We can blacklist it if it doesn't work.

**Comment by dtdang** [comment]
> > It's not just the infura rpc that shows this error. I've also noticed it when it is trying to connect with tenderly node as well ["https://sepolia.gateway.tenderly.co",](https://github.com/ApeWorX/evmchains/blob/79da8102cb207c784f3b347e8766bec77ee65924/evmchains/chains.py#L533C17-L533C55)
> 
> The linked tenderly RPC doesn't have the same issue with the required keys. If you can repro and confirm that error, can you post it? We can blacklist it if it doesn't work.

You were right. Seems to be just an issue from just infura when I'm trying to connect to the network.
